export interface ModelInterface {
	setSource(source:string):void;
	getSource():string;
	setSchema(schema:string):void;
	getSchema():string;
	setUrl();
	getUrl();
	setWriteUrl();
	getWriteUrl();
	setReadUrl();
	getReadUrl();
	setDefaultRequestMethod();
	getDefaultRequestMethod();
	setWriteRequestMethod();
	getWriteRequestMethod();
	setReadRequestMethod();
	getReadRequestMethod();
	setTableColumns();
	getTableColumns();
	create();
	update();
	delete();
	save();
	count();
	find();
	findFirst();
	query();
}